version: "3.8"
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - "5222:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
